name: Verify Pull Request
on: pull_request

jobs:
  verify-pr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          overwrite-settings: false

      - run: |
          ./mvnw clean verify \
            --batch-mode --no-transfer-progress
