name: Verify Main
on:
  push:
    branches:
      - main

jobs:
  verify-main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          overwrite-settings: false

      - run: |
          ./mvnw clean verify \
            --batch-mode --no-transfer-progress
